name = "virtualobby-api"
main = "api/worker.js"
compatibility_date = "2024-01-01"

# D1 Database
[[d1_databases]]
binding = "DB"
database_name = "virtualobby-db"
database_id = "d3c8c0da-6133-479e-9214-ce05498061c3"

# R2 Bucket for document photos
[[r2_buckets]]
binding = "R2_DOCS"
bucket_name = "virtualobby-docs"
